site_name: Revanth Lol
site_url: https://revanthlol.github.io
repo_url: https://github.com/revanthlol/revanthlol.github.io
repo_name: revanthlol/revanthlol.github.io

theme:
  name: material
  language: en
  palette:
    - scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: default
      primary: black
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy
    - search.highlight
    - search.share

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight

nav:
  - Home: index.md

